timezone: Europe/Paris
lang: fr-FR
google_analytics: 'UA-74142838-3'
title: Blog ISITIX
markdown: kramdown
paginate: 10
show_drafts: false
paginate_path: "/blog/page:num"
excerpt_separator: <!--break-->
url: "http://blog.isitix.com"
plugins:
  - jekyll-sitemap
sass:
  style: compressed
